In [102]:
import pandas as pd

titanic = pd.read_csv("bases/titanic.csv")

novo = titanic.groupby("Sex")["Age"].mean().to_frame(name="media_idade")

vivos = titanic[titanic["Survived"] == 1].groupby("Sex").count()
mortos = titanic[titanic["Survived"] == 0].groupby("Sex").count()

novo["vivos"] = vivos["PassengerId"]
novo["mortos"] = mortos["PassengerId"]

print(novo)

        media_idade  vivos  mortos
Sex
female    27.915709    233      81
male      30.726645    109     468

In [103]:
train = pd.read_csv("bases/train.csv")
homem = train.Sex[train["Sex"] == "male"].count()
mulheres = train.Sex[train["Sex"] == "female"].count()
total = train["Sex"].count()

print(f"Homens no titanic: {(homem/total)*100} %")
print(f"Mulheres no titanic: {(mulheres/total)*100} %")

Homens no titanic: 64.75869809203144 %
Mulheres no titanic: 35.24130190796858 %

In [104]:
gatos = pd.read_csv("bases/cat_breeds_clean.csv",sep=";")

angora = gatos[gatos["Breed"] == "Angora"]
angora.head()

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
0,Angora,0.25,3,female,False,19,2.0,white,solid,blue,False,wet,46,16,France,43.296482,5.369780
1,Angora,0.33,4,male,False,19,2.5,white,solid,blue,False,wet,48,16,France,43.611660,3.877710
2,Angora,0.50,6,male,False,20,2.8,black,solid,green,False,wet,41,11,France,44.837789,-0.579180
3,Angora,0.50,6,female,False,21,3.0,white,solid,blue,False,wet,24,8,France,43.611660,3.877710
4,Angora,0.50,6,male,False,21,3.0,red/cream,tabby,green,False,wet,51,10,France,48.864716,2.349014

In [105]:
europeus = gatos[(gatos["Country"] == "France") | (gatos["Country"] == "UK") | (gatos["Country"] == "Germany")]

europeus.head()

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
0,Angora,0.25,3,female,False,19,2.0,white,solid,blue,False,wet,46,16,France,43.296482,5.369780
1,Angora,0.33,4,male,False,19,2.5,white,solid,blue,False,wet,48,16,France,43.611660,3.877710
2,Angora,0.50,6,male,False,20,2.8,black,solid,green,False,wet,41,11,France,44.837789,-0.579180
3,Angora,0.50,6,female,False,21,3.0,white,solid,blue,False,wet,24,8,France,43.611660,3.877710
4,Angora,0.50,6,male,False,21,3.0,red/cream,tabby,green,False,wet,51,10,France,48.864716,2.349014

In [265]:
print(gatos.columns)

Index(['Breed', 'Age_in_years', 'Age_in_months', 'Gender',
       'Neutered_or_spayed', 'Body_length', 'Weight', 'Fur_colour_dominant',
       'Fur_pattern', 'Eye_colour', 'Allowed_outdoor', 'Preferred_food',
       'Owner_play_time_minutes', 'Sleep_time_hours', 'Country', 'Latitude',
       'Longitude'],
      dtype='object')

In [287]:
paises_laranja = gatos.Country[gatos["Fur_colour_dominant"] == "red/cream"]
paises_laranja.head()

4     France
7     France
14    France
28    France
52    France
Name: Country, dtype: object

In [106]:
seis = gatos[gatos["Age_in_months"]>6]

def porcentagem(linha):
    return linha["Weight"] / linha["Body_length"]
    
per = seis.apply(porcentagem, axis=1)
seis["Porcentagem"] = per

seis.head()

C:\Users\disrct\AppData\Local\Temp\ipykernel_16944\2563878109.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seis["Porcentagem"] = per

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude,Porcentagem
6,Angora,0.58,7,male,False,22,3.0,white,solid,amber,False,wet,47,9,France,47.218371,-1.553621,0.136364
7,Angora,0.58,7,male,False,23,3.0,red/cream,solid,blue,False,wet,55,11,France,47.218371,-1.553621,0.130435
8,Angora,0.58,7,female,False,25,3.0,black,tortie,blue,False,wet,20,12,France,43.296482,5.369780,0.120000
9,Angora,0.67,8,female,False,25,3.0,white,solid,blue,False,wet,33,17,France,44.837789,-0.579180,0.120000
10,Angora,0.67,8,female,False,26,3.0,black,solid,green,False,wet,39,18,France,43.296482,5.369780,0.115385

In [312]:
machos = gatos[gatos["Gender"] == "male"]

machos[["Breed", "Age_in_years", "Weight"]].head()

    Breed  Age_in_years  Weight
1  Angora          0.33     2.5
2  Angora          0.50     2.8
4  Angora          0.50     3.0
6  Angora          0.58     3.0
7  Angora          0.58     3.0

In [368]:
print(gatos.columns)

Index(['Breed', 'Age_in_years', 'Age_in_months', 'Gender',
       'Neutered_or_spayed', 'Body_length', 'Weight', 'Fur_colour_dominant',
       'Fur_pattern', 'Eye_colour', 'Allowed_outdoor', 'Preferred_food',
       'Owner_play_time_minutes', 'Sleep_time_hours', 'Country', 'Latitude',
       'Longitude'],
      dtype='object')

In [ ]:
ragdoll = gatos[gatos["Breed"] == "Ragdoll"]

def dia(linha):
    return linha["Sleep_time_hours"] / 24 * 100

perD = ragdoll.apply(dia,axis=1)
ragdoll["Porcentagem"] = perD

ragdoll.head()

C:\Users\disrct\AppData\Local\Temp\ipykernel_5368\2189955867.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ragdoll["Porcentagem"] = perD

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude,Porcentagem
606,Ragdoll,0.25,3,female,True,21,3.1,red/cream,bicolor,blue,False,wet,60,10,USA,38.895110,-77.036370,41.666667
607,Ragdoll,0.33,4,male,False,21,3.0,red/cream,colorpoint,blue,False,dry,21,16,USA,37.774930,-122.419420,66.666667
608,Ragdoll,0.33,4,female,False,21,3.0,seal,tortie,green,False,wet,31,16,UK,51.507351,-0.127758,66.666667
609,Ragdoll,0.33,4,male,False,21,3.0,seal,colorpoint,blue,False,wet,16,17,UK,53.480759,-2.242631,70.833333
610,Ragdoll,0.33,4,female,False,21,3.3,red/cream,bicolor,blue,False,dry,14,16,UK,52.486244,-1.890401,66.666667

In [372]:
soma = gatos["Body_length"].sum()
print("SOMA:", soma)

SOMA: 47128

In [374]:
media = gatos["Sleep_time_hours"].mean()
print("MÉDIA:", round(media,2))

MÉDIA: 15.89

In [429]:
naoseiporqueestádandoerrado = gatos.Weight[(gatos["Age_in_months"] > 3) & (gatos["Age_in_months"] < 12)].sum()
print(naoseiporqueestádandoerrado)

172.80000000000004

In [430]:
gatos.columns

Index(['Breed', 'Age_in_years', 'Age_in_months', 'Gender',
       'Neutered_or_spayed', 'Body_length', 'Weight', 'Fur_colour_dominant',
       'Fur_pattern', 'Eye_colour', 'Allowed_outdoor', 'Preferred_food',
       'Owner_play_time_minutes', 'Sleep_time_hours', 'Country', 'Latitude',
       'Longitude'],
      dtype='object')

In [474]:
def razao(linha):
    return linha["Body_length"] / linha["Age_in_years"]

pretoebranco = gatos[(gatos["Fur_colour_dominant"] == "black") | (gatos["Fur_colour_dominant"] == "white")]
pretoebranconorte = pretoebranco[(pretoebranco["Country"] == "USA") | (pretoebranco["Country"] == "Canada")]

per = pretoebranconorte.apply(razao,axis=1)
pretoebranconorte["porcentagem"] = per

média = pretoebranconorte['porcentagem'].mean()

print("Média da razão entre comprimento e idade dos gatos brancos e pretos da América do Norte:", round(média,2))

Média da razão entre comprimento e idade dos gatos brancos e pretos da América do Norte: 14.4

C:\Users\disrct\AppData\Local\Temp\ipykernel_5368\529207999.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pretoebranconorte["porcentagem"] = per

In [1]:
import pandas as pd

dados = pd.read_csv("bases/dados.csv",encoding="latin-1")

AAA = dados[(dados["quartos"] == 3) & (dados["bairro"] == "Tijuca") & (dados["area"] > 130)]
certo = AAA[AAA['preco'] == AAA["preco"].min()]

certo

      condominio  quartos  suites  vagas  area  bairro   preco      pm2
1971         480        3     1.0    3.0   142  Tijuca  600000  4225.35

In [29]:
master = pd.read_csv("bases/master.csv",sep=",")

def país(linha):
    return linha["country-year"][:-4]

def ano(linha):
    return linha["country-year"][-4:]

c = master.apply(país,axis=1)
y = master.apply(ano,axis=1)

master = master.drop(columns=["country-year","HDI for year"])

master["country"] = c
master["year"] = y 

master[(master['country'] == "Brazil") & (master['year'] == '1987') & (master['sex'] == "female") & (master['generation'] == "Boomers")]

,country,year,sex,age,suicides_no,population,suicides/100k pop,gdp_for_year ($),gdp_per_capita ($),generation
4204,Brazil,1987,female,25-34 years,266,11393405,2.33,"294,084,112,393",2394,Boomers

In [39]:
tips = pd.read_csv("bases/tips.csv", sep=";")

tips.head()

def gorgeta(linha):
    return (round((linha['tip'] / linha['total_bill']) * 100,2))

per = tips.apply(gorgeta,axis=1)

tips["tip_pct"] = per

tips[tips["tip_pct"] == tips["tip_pct"].max()]

     total_bill   tip   sex smoker  day    time  servings  tip_pct
172        7.25  5.15  Male    Yes  Sun  Dinner         2    71.03

In [56]:
mediaporsexo = round(tips.groupby("sex")['tip'].mean(),2)
print(mediaporsexo)

sex
Female    2.83
Male      3.09
Name: tip, dtype: float64

In [80]:
print(tips['servings'].count())

244

In [61]:
media = tips['tip'].mean()

def pagaruim(linha):
    if linha['tip'] < media:
        return "mau pagador"
    else:
        return "bom pagador"
    
x = tips.apply(pagaruim,axis=1)

tips["class"] = x

tips.head()

   total_bill   tip     sex smoker  day    time  servings        class
0       16.99  1.01  Female     No  Sun  Dinner         2  mau pagador
1       10.34  1.66    Male     No  Sun  Dinner         3  mau pagador
2       21.01  3.50    Male     No  Sun  Dinner         3  bom pagador
3       23.68  3.31    Male     No  Sun  Dinner         2  bom pagador
4       24.59  3.61  Female     No  Sun  Dinner         4  bom pagador

In [92]:
maus = tips[tips['class'] == 'mau pagador'].groupby("day")['class'].count()

maus[maus == maus.max()]

day
Sat    45
Name: class, dtype: int64

In [100]:
maus = tips[tips['class'] == 'mau pagador']

fumantes = maus.groupby('smoker')['class'].count().to_frame(name="Maus pagadores")
print(fumantes)

        Maus pagadores
smoker
No                  80
Yes                 43

In [76]:
new = tips[(tips['servings'] > 3) & (tips['time'] == 'Dinner') & (tips['smoker'] == 'No') & (tips['day'] == 'Sat')]

new['tip'].mean()

4.8